Modules/Crm/Routes/web.php
<?php

Route::prefix('crm')->group(function() {
    Route::get('/', 'CrmController@index')->name('crm');

    Route::get('get-employee-name-id', 'CrmController@getEmployeeNameId')->name('get-employee-name-id');

    Route::prefix('clients')->group(function () {
        Route::apiResources([
            'groups'  => 'ClientGroupsController',
            'clients' => 'ClientsController',
            'contacts' => 'ClientContactsController',
        ]);
        Route::get('client-groups', 'ClientsController@groups')->name('client-groups');
        Route::get('client-status-change', 'ClientsController@changeActivationStatus')->name('client-status-change');
        Route::get('client-name-id', 'ClientsController@getClientNameId')->name('client-name-id');
        Route::get('client-contact-edit', 'ClientContactsController@edit')->name('client-contact-edit');
        Route::post('client-contact-photo-update', 'ClientContactsController@updateProfilePhoto')->name('client-contact-photo-update');
    });
    Route::prefix('items')->group(function () {
        Route::apiResources([
            'unit-types'  => 'UnitTypesController',
            'items'  => 'ItemsController',
        ]);
        Route::get('items-id-name', 'ItemsController@getItemsIdName')->name('items-id-name');
    });
    Route::prefix('projects')->group(function () {
        Route::apiResources([
            'client-projects'  => 'ClientProjectsController',
            'porject-statues'  => 'ProjectStatusesController',
            'tasks'  => 'ProjectTasksController',
        ]);
        Route::get('project-details/{id}', 'ClientProjectsController@projectDetails')->name('project-details');
        Route::get('project-tasks/{projectid}', 'ClientProjectsController@projectTasks')->name('project-tasks');
        Route::get('project-name-id', 'ClientProjectsController@getProjectNameId')->name('project-name-id');
        Route::get('specific-client-project-name-id', 'ClientProjectsController@getSpecificClientProjectNameId')->name('specific-client-project-name-id');
        Route::get('client-project-id-name', 'ClientProjectsController@getClientProjectIdName')->name('client-project-id-name');
        Route::put('update-task-status', 'ProjectTasksController@updateTaskStatus')->name('update-task-status');
        Route::get('specific-client-projects', 'ClientProjectsController@specificClientProjects')->name('specific-client-projects');
    });
    Route::resource('invoices', 'InvoicesController');
    Route::resource('invoice-items', 'InvoiceItemsController');
    Route::get('specific-client-invoices', 'InvoicesController@specificClientInvoices')->name('specific-client-invoices');
    Route::resource('payments', 'PaymentsController');
    Route::get('estimate-requests', 'EstimatesController@estimateRequests')->name('estimate-requests');
    Route::get('estimate-request-show/{id}', 'EstimatesController@estimateRequestShow')->name('estimate-request-show');
    Route::put('estimate-request-status-update', 'EstimatesController@estimateRequestStatusUpdate')->name('estimate-request-status-update');
    Route::resource('estimates', 'EstimatesController');
    Route::get('estimate-details/{id}', 'EstimatesController@estimateDetails')->name('estimate-details');
    Route::put('estimate-mark-as-project', 'EstimatesController@markAsProject')->name('estimate-mark-as-project');
    Route::put('update-estimate', 'EstimatesController@updateEstimate')->name('update-estimate');
    Route::resource('estimate-items', 'EstimatedItemsController');
    Route::get('estimate-discount', 'EstimatedItemsController@estimateDiscount')->name('estimate-discount');
    Route::put('estimate-discount/{id}', 'EstimatedItemsController@estimateDiscountUpdate');
    Route::get('esitmate-pdf-generate/{id}', 'EstimatedItemsController@estimatePdfGenerate')->name('esitmate-pdf-generate');

    Route::get('get-invoice-to-pay', 'InvoicesController@getInvoiceToPay')->name('get-invoice-to-pay');
    Route::prefix('settings')->group(function () {
        Route::get('other-setup', 'SettingsController@OtherSetup')->name('other-setup');
        Route::apiResources([
            'payment-methods' => 'PaymentMethodsController',
            'task-statuses'  => 'TaskStatusesController',
            'taxes'  => 'TaxesController',
        ]);
    });
});

Modules/Crm/Http/Controllers/SettingsController.php
<?php

namespace Modules\Crm\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {

        return view('crm::index');
    }
    public function OtherSetup()
    {
        return view('crm::settings.other-setup');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('crm::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        return view('crm::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return view('crm::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Crm/Resources/views/settings/payment-methods.blade.php
@extends('crm::layouts.master')
@section('title')
{{__('Home')}}
@endsection
@section('content')
  
<div class="container-fluid">
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-credit-card bg-blue"></i>
                    <div class="d-inline">
                        <h5>{{__('Payment Methods')}}</h5>
                        <span>{{__('Here is available payment methods. Create new one if you have.')}}</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{route('crm')}}"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="javascript:void(0)">{{__('Settings')}}</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">{{__('Other Setup')}}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="float-left"> {{__('Payment Methods')}} </h3>
                </div>
                <div class="card-body">
                    <div class="dt-responsive dt-p-lf">
                        <table id="paymentMethodTable" class="table nowrap">
                            <thead>
                                <tr>
                                    <th>{{__('ID')}}</th>
                                    <th>{{__('Title')}}</th>
                                    <th class="text-right"></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-header d-block">
                    <h3 class="float-left" id="pmHeader"> {{__('New Payment Method')}} </h3>
                </div>
                <div class="card-body">
                    <div class="leftForm">
                        <div class="form-group row">
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" class="form-control" placeholder="{{__('title here')}}" name="paymentmethod" id="paymentmethod" required>
                            </div>
                            <div class="col-sm-4 col-lg-4">
                                <button type="button" id="pmBtn" class="btn btn-primary save-payment-method">{{__('Save')}}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('extraCSS')

@endsection
@section('extraJS')

<script>
    let pMethodTbl;
    $(document).ready(function () {
        /*------load payment method start------*/
        pMethodTbl = $('#paymentMethodTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('payment-methods.index') }}",
            deferRender: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
                {data: 'title', name: 'title'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });
        /*------load payment method end--------*/


        /*---------------saving payment method start-----------------*/
        $(document).on('click', '.save-payment-method', function(e){
            e.preventDefault();
            let paymentmethod = $("#paymentmethod").val();
            if (paymentmethod == '') {
                alert("Payment method title field required!");
                $("#paymentmethod").focus();
                return false;
            }
            $.ajax({
                url: '{{route('payment-methods.store')}}',
                type: 'POST',
                data: {
                    title: paymentmethod
                },
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    $("#paymentmethod").val('');
                    showSuccessToast('{{__("Added Successfully")}}');
                    pMethodTbl.draw(false);
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                }
            });
        });
        /*---------------saving payment method end-------------------*/


        /*---------------edit payment method start-----------------*/
        $(document).on('click', '.edit-method', function(){
            let id = $(this).val();
            $.ajax({
                url: '{{route('payment-methods.index')}}/' + id,
                type: 'GET',
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                   $("#paymentmethod").val(response.title);
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                    console.log(data);
                }
            });
            $("#pmHeader").text('{{__("Edit Payment Method")}}');
            $("#pmBtn").removeClass('save-payment-method').addClass('update-payment-method').text('{{__("Update")}}').val(id);
        });
        /*---------------edit payment method start-----------------*/


        /*---------------updating payment method start-----------------*/
        $(document).on('click', '.update-payment-method', function(e){
            e.preventDefault();
            let paymentmethod = $("#paymentmethod").val();
            if (paymentmethod == '') {
                alert("Payment method title field required!");
                $("#paymentmethod").focus();
                return false;
            }

            let id = $(this).val();

            $.ajax({
                url: '{{route('payment-methods.index')}}/' + id,
                type: 'PUT',
                data: {
                    title: paymentmethod
                },
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    console.log(response);
                    $("#paymentmethod").val('');
                    showSuccessToast('{{__("Updated Successfully")}}');
                    pMethodTbl.draw(false);
                    $("#pmHeader").text('{{__("New Payment Method")}}');
                    $("#pmBtn").removeClass('update-payment-method').addClass('save-payment-method').text('{{__("Save")}}');
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                }
            });
        });
        /*---------------updating payment method end-------------------*/
    });
</script>
@endsection