Modules/Crm/Routes/web.php
<?php

Route::prefix('crm')->group(function() {
    Route::get('/', 'CrmController@index')->name('crm');

    Route::get('get-employee-name-id', 'CrmController@getEmployeeNameId')->name('get-employee-name-id');

    Route::prefix('clients')->group(function () {
        Route::apiResources([
            'groups'  => 'ClientGroupsController',
            'clients' => 'ClientsController',
            'contacts' => 'ClientContactsController',
        ]);
        Route::get('client-groups', 'ClientsController@groups')->name('client-groups');
        Route::get('client-status-change', 'ClientsController@changeActivationStatus')->name('client-status-change');
        Route::get('client-name-id', 'ClientsController@getClientNameId')->name('client-name-id');
        Route::get('client-contact-edit', 'ClientContactsController@edit')->name('client-contact-edit');
        Route::post('client-contact-photo-update', 'ClientContactsController@updateProfilePhoto')->name('client-contact-photo-update');
    });
    Route::prefix('items')->group(function () {
        Route::apiResources([
            'unit-types'  => 'UnitTypesController',
            'items'  => 'ItemsController',
        ]);
        Route::get('items-id-name', 'ItemsController@getItemsIdName')->name('items-id-name');
    });
    Route::prefix('projects')->group(function () {
        Route::apiResources([
            'client-projects'  => 'ClientProjectsController',
            'porject-statues'  => 'ProjectStatusesController',
            'tasks'  => 'ProjectTasksController',
        ]);
        Route::get('project-details/{id}', 'ClientProjectsController@projectDetails')->name('project-details');
        Route::get('project-tasks/{projectid}', 'ClientProjectsController@projectTasks')->name('project-tasks');
        Route::get('project-name-id', 'ClientProjectsController@getProjectNameId')->name('project-name-id');
        Route::get('specific-client-project-name-id', 'ClientProjectsController@getSpecificClientProjectNameId')->name('specific-client-project-name-id');
        Route::get('client-project-id-name', 'ClientProjectsController@getClientProjectIdName')->name('client-project-id-name');
        Route::put('update-task-status', 'ProjectTasksController@updateTaskStatus')->name('update-task-status');
        Route::get('specific-client-projects', 'ClientProjectsController@specificClientProjects')->name('specific-client-projects');
    });
    Route::resource('invoices', 'InvoicesController');
    Route::resource('invoice-items', 'InvoiceItemsController');
    Route::get('specific-client-invoices', 'InvoicesController@specificClientInvoices')->name('specific-client-invoices');
    Route::resource('payments', 'PaymentsController');
    Route::get('estimate-requests', 'EstimatesController@estimateRequests')->name('estimate-requests');
    Route::get('estimate-request-show/{id}', 'EstimatesController@estimateRequestShow')->name('estimate-request-show');
    Route::put('estimate-request-status-update', 'EstimatesController@estimateRequestStatusUpdate')->name('estimate-request-status-update');
    Route::resource('estimates', 'EstimatesController');
    Route::get('estimate-details/{id}', 'EstimatesController@estimateDetails')->name('estimate-details');
    Route::put('estimate-mark-as-project', 'EstimatesController@markAsProject')->name('estimate-mark-as-project');
    Route::put('update-estimate', 'EstimatesController@updateEstimate')->name('update-estimate');
    Route::resource('estimate-items', 'EstimatedItemsController');
    Route::get('estimate-discount', 'EstimatedItemsController@estimateDiscount')->name('estimate-discount');
    Route::put('estimate-discount/{id}', 'EstimatedItemsController@estimateDiscountUpdate');
    Route::get('esitmate-pdf-generate/{id}', 'EstimatedItemsController@estimatePdfGenerate')->name('esitmate-pdf-generate');

    Route::get('get-invoice-to-pay', 'InvoicesController@getInvoiceToPay')->name('get-invoice-to-pay');
    Route::prefix('settings')->group(function () {
        Route::get('other-setup', 'SettingsController@OtherSetup')->name('other-setup');
        Route::apiResources([
            'payment-methods' => 'PaymentMethodsController',
            'task-statuses'  => 'TaskStatusesController',
            'taxes'  => 'TaxesController',
        ]);
    });
});

Modules/Crm/Entities/Client.php
<?php

namespace Modules\Crm\Entities;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
	protected $connection = 'crm';
    protected $fillable = ['client_group_id', 'name', 'phone', 'email', 'address', 'city', 'state', 'zip', 'country', 'website', 'vat_number'];

    public function clientgroup()
    {
        return $this->belongsTo(ClientGroup::class, 'client_group_id', 'id');
    }
    
    public function clientcontact()
    {
    	return $this->hasMany(ClientContact::class, 'client_id', 'id');
    }

    public function primarycontact()
    {
    	return $this->hasOne(ClientContact::class, 'client_id', 'id');
    }

    public function project()
    {
        return $this->hasMany(ClientProject::class, 'client_id', 'id');
    }
}

Modules/Crm/Http/Controllers/ClientsController.php
<?php

namespace Modules\Crm\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;
use Modules\Crm\Entities\Client;
use Modules\Crm\Entities\ClientContact;
use Modules\Crm\Entities\ClientGroup;
use Modules\Crm\Entities\ClientProject;
use Modules\Crm\Entities\Invoice;
use Yajra\DataTables\Facades\DataTables;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $clients = Client::with(['primarycontact' => function($query){
                $query->where('is_primary_contact', '=', 1);
            }])->orderBy('created_at', 'desc')->get();
            //$clients = Client::with('primarycontact')->get();
            return Datatables::of($clients)
                ->addIndexColumn()
                ->addColumn('name', function ($client) {
                    $company = '<a href="'.route('clients.show', $client->id).'" class="clickable">'.ucwords($client->name).'</a>';
                    return $company;
                })
                ->addColumn('primarycontact', function ($client) {
                    if ($client->primarycontact) {
                        if ($client->primarycontact->photo == '' && $client->primarycontact->gender == 1) {
                            $fullname = '<a href="'.route('contacts.show', $client->primarycontact->id).'" class="clickable"><img class="img-responsive contact-person-photo-small" src="'.asset('storage/crm/male-avatar.png').'"/> '.ucwords($client->primarycontact->first_name.' '.$client->primarycontact->last_name).'</a>';
                        }
                        if ($client->primarycontact->photo == '' && $client->primarycontact->gender == 2) {
                            $fullname = '<a href="'.route('contacts.show', $client->primarycontact->id).'" class="clickable"><img class="img-responsive contact-person-photo-small" src="'.asset('storage/crm/female-avatar.png').'"/> '.ucwords($client->primarycontact->first_name.' '.$client->primarycontact->last_name).'</a>';
                        }
                        if ($client->primarycontact->photo == '' && $client->primarycontact->gender == 3) {
                            $fullname = '<a href="'.route('contacts.show', $client->primarycontact->id).'" class="clickable"><img class="img-responsive contact-person-photo-small" src="'.asset('storage/crm/other-avatar.png').'"/> '.ucwords($client->primarycontact->first_name.' '.$client->primarycontact->last_name).'</a>';
                        }
                        if ($client->primarycontact->photo) {
                            $fullname = '<a href="'.route('contacts.show', $client->primarycontact->id).'" class="clickable"><img class="img-responsive contact-person-photo-small" src="'.asset('storage/crm/contact/'.$client->primarycontact->photo.'').'"/> '.ucwords($client->primarycontact->first_name.' '.$client->primarycontact->last_name).'</a>';
                        }
                    }else{
                        $fullname= '<p class="font-weight-bolder">Sorry, Not Found!</p>';
                    }
                    
                    //$fullname = $client->primarycontact;
                    return $fullname;
                })
                ->addColumn('created_at', function ($client) {
                    $createdAt = date('d M Y h:i a', strtotime($client->created_at));
                    
                    return $createdAt;
                })
                ->addColumn('action', function ($client) {
                    if ($client->status == 1) {
                        $btn = '<div style="text-align: right;"><label class="switch"><input type="checkbox" checked onclick="changeStatus('.$client->id.')"><span class="slider"></span></label></div>';
                    }
                    if ($client->status == 0) {
                        $btn = '<div style="text-align: right;"><label class="switch"><input type="checkbox" onclick="changeStatus('.$client->id.')"><span class="slider"></span></label></div>';
                    }
                    
                    return $btn;
                })
                ->rawColumns(['name', 'primarycontact', 'created_at','action'])
                ->make(true);
        }
        return view('crm::.clients.list');
    }

    /**
    *
    *get client name and id only for select option
    *
    */
    public function getClientNameId()
    {
        return Client::orderBy('name')->get(['id', 'name']);
    }

    public function groups()
    {
        return ClientGroup::all();
    }
    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('crm::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            //'email' => 'nullable|unique:crm.clients,email',
            //'phone' => 'required|unique:crm.clients,phone',

        ];
        $messages = [
            'name.required' => 'The name field is required.',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();

        $client = new Client();
        $client->name = $request->name;
        $client->client_group_id = $request->clientgroup;
        $client->phone = $request->phone;
        $client->email = $request->email;
        $client->website = $request->website;
        $client->vat_number = $request->vatnumber;
        $client->address = $request->address;
        $client->city = $request->city;
        $client->state = $request->state;
        $client->zip = $request->zip;
        $client->country = $request->country;
        $client->save();

        $clientContact = new ClientContact();
        $clientContact->first_name = $request->firstname;
        $clientContact->last_name = $request->lastname;
        $clientContact->gender = $request->gender;
        $clientContact->job_title = $request->jobtitle;
        $clientContact->phone = $request->contact_person_phone;
        $clientContact->email = $request->contact_person_email;
        $clientContact->skype = $request->contact_person_skype;
        $clientContact->whatsapp = $request->contact_person_whats_app;
        if ($request->contact_person_password) {
            $password = $request->contact_person_password;
        }else{
            $password = '12345678';
        }
        $clientContact->password = Hash::make($password);
        $clientContact->is_primary_contact = 1;
        $clientContact->is_login_access = 1;
        $client->clientcontact()->save($clientContact);

        return $client;

    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //$client = Client::with('clientcontact')->find($id);
        $client = Client::with('clientgroup')->find($id);
        $clientProjects = ClientProject::where('client_id', $id)->count();

        // $start = microtime(true);
        // $iValues = Invoice::where('client_id', $id)->sum('invoice_value');
        // $paymentsReceived = Invoice::where('client_id', $id)->sum('payment_received');
        // return $time = microtime(true) - $start;

        //$start = microtime(true);
        $invoicesPaymentRecord = Invoice::select([
            DB::raw("SUM(invoice_value) as invoicesValues"),
            DB::raw("SUM(payment_received) as paymentsReceived"),
        ])->where('client_id', $id)->first();
        //return $time = microtime(true) - $start;
        return view('crm::.clients.details', compact('client', 'clientProjects', 'invoicesPaymentRecord'));
        // return view('crm::.clients.details', compact('client', 'clientProjects', 'invoicesValues'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return view('crm::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name'     => 'required',
            'email'    => 'required|unique:crm.clients,email,'. $id .'',
            'phone'    => 'required|unique:crm.clients,phone,'. $id .'',
            'address'  => 'required',

        ];
        $messages = [
            'name.required' => 'The name field is required.',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();

        $client = Client::find($id);
        if (!$request->status) {
            if ($client->status == 1) {
                $status = 0;
            }else{
                $status = 1;
            }
        }else{
            $status = $request->status;
        }
        $client->client_group_id = $request->clientgroup;
        $client->name            = $request->name;
        $client->phone           = $request->phone;
        $client->email           = $request->email;
        $client->address         = $request->address;
        $client->city            = $request->city;
        $client->state           = $request->state;
        $client->zip             = $request->zip;
        $client->country         = $request->country;
        $client->website         = $request->website;
        $client->vat_number      = $request->vatnumber;
        $client->status          = $status;
        $client->save();

    }

    /**
     * Remove the specified resource from storage.

Modules/Crm/Resources/views/clients/groups.blade.php
@extends('crm::layouts.master')
@section('title')
{{__('Home')}}
@endsection
@section('content')
  
<div class="container-fluid">
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-aperture bg-blue"></i>
                    <div class="d-inline">
                        <h5>{{__('Client Groups')}}</h5>
                        <span>{{__('Client groups define in which category they are(Ex: General, VIP, Low Budget etc.)')}}</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{route('crm')}}"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="javascript:void(0)">{{__('Client')}}</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">{{__('Groups')}}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-block">
                    <h3 class="float-left"> {{__('Groups')}} </h3>
                    <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#addModal"> + {{__('Add Group')}}
                    </button>
                </div>
                <div class="card-body">
                    <div class="dt-responsive">
                        <table id="#" class="table nowrap">
                            <thead>
                            <tr>
                                <th>{{__('ID')}}</th>
                                <th>{{__('Group Name')}}</th>
                                <th>{{__('Description')}}</th>
                                <th class="text-right">{{__('Action')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Group Modal -->
<div class="modal animated zoomIn faster" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">{{__('Group')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="Form" action="javascript:void(0)">
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-4 col-lg-4 col-form-label">{{__('New Group')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <input type="text" class="form-control" placeholder="{{__('name here')}}" name="name" id="name" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-lg-4 col-form-label" for="exampleTextarea1">{{__('Description')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <textarea class="form-control" id="exampleTextarea1" rows="4" placeholder="{{__('description here')}}.." name="desc" id="desc"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('Close')}}</button>
                    <button type="submit" class="btn btn-primary save-btn"></button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('extraJS')
<script>
    $(document).ready(function () {
        var gTable = $('.table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('groups.index') }}",
            deferRender: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'desc', name: 'desc'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });
        $('.modal').on('hidden.bs.modal', function (e) {
            $('form').trigger("reset");
        });

        /*--------------create and edit form start---------*/
        $('#addModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget);
            let purpose = button.data('whatever');
            let modal = $(this);
            if (purpose) {
                modal.find('.modal-title').text('{{__("Edit Group")}}');
                let id = button.data('id');
                $.ajax({
                    url: '{{ route('groups.index') }}/' + id,
                    type: 'GET',
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                       // modal.find('input[name=id]').val(response.id);
                       modal.find('input[name=name]').val(response.name);
                       modal.find('input[name=desc]').val(response.desc);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        alert(msg);
                    }
                });
                modal.find('button[type=submit]').removeClass('save-btn').addClass('update-btn').text('{{__("Update")}}').val(id);
            }else{
                modal.find('.modal-title').text('{{__("Add Group")}}');
                modal.find('button[type=submit]').removeClass('update-btn').addClass('save-btn').text('{{__("Save")}}');
            }
        });
        /*--------------create and edit form end-----------*/



        /*--------------save start---------*/
        $(document).on('click', '.save-btn', function () {
            let data = $('#Form').serialize();
            $.ajax({
                url: '{{route('groups.store')}}',
                type: 'POST',
                data: data,
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    $('#addModal').modal('toggle');
                    $('#Form').trigger("reset");
                    showSuccessToast('{{__("Added Successfully")}}');
                    gTable.draw(false);
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                }
            });
        });
        /*--------------save end----------*/


        /*--------------update start---------*/
        $(document).on('click', '.update-btn', function () {
            let id = this.value;
            let data = $('#Form').serialize();
            $.ajax({
                url: "{{ route('groups.index')}}/" + id,
                type: 'PUT',
                data: data,
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    $('#addModal').modal('toggle');
                    $('#Form').trigger("reset");
                    showSuccessToast('{{__("Updated Successfully")}}');
                    gTable.draw(false);
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                }
            });
           
        });
        /*--------------update end----------*/

    });
</script>
@endsection