Modules/Crm/Routes/web.php
<?php

Route::prefix('crm')->group(function() {
    Route::get('/', 'CrmController@index')->name('crm');

    Route::get('get-employee-name-id', 'CrmController@getEmployeeNameId')->name('get-employee-name-id');

    Route::prefix('clients')->group(function () {
        Route::apiResources([
            'groups'  => 'ClientGroupsController',
            'clients' => 'ClientsController',
            'contacts' => 'ClientContactsController',
        ]);
        Route::get('client-groups', 'ClientsController@groups')->name('client-groups');
        Route::get('client-status-change', 'ClientsController@changeActivationStatus')->name('client-status-change');
        Route::get('client-name-id', 'ClientsController@getClientNameId')->name('client-name-id');
        Route::get('client-contact-edit', 'ClientContactsController@edit')->name('client-contact-edit');
        Route::post('client-contact-photo-update', 'ClientContactsController@updateProfilePhoto')->name('client-contact-photo-update');
    });
    Route::prefix('items')->group(function () {
        Route::apiResources([
            'unit-types'  => 'UnitTypesController',
            'items'  => 'ItemsController',
        ]);
        Route::get('items-id-name', 'ItemsController@getItemsIdName')->name('items-id-name');
    });
    Route::prefix('projects')->group(function () {
        Route::apiResources([
            'client-projects'  => 'ClientProjectsController',
            'porject-statues'  => 'ProjectStatusesController',
            'tasks'  => 'ProjectTasksController',
        ]);
        Route::get('project-details/{id}', 'ClientProjectsController@projectDetails')->name('project-details');
        Route::get('project-tasks/{projectid}', 'ClientProjectsController@projectTasks')->name('project-tasks');
        Route::get('project-name-id', 'ClientProjectsController@getProjectNameId')->name('project-name-id');
        Route::get('specific-client-project-name-id', 'ClientProjectsController@getSpecificClientProjectNameId')->name('specific-client-project-name-id');
        Route::get('client-project-id-name', 'ClientProjectsController@getClientProjectIdName')->name('client-project-id-name');
        Route::put('update-task-status', 'ProjectTasksController@updateTaskStatus')->name('update-task-status');
        Route::get('specific-client-projects', 'ClientProjectsController@specificClientProjects')->name('specific-client-projects');
    });
    Route::resource('invoices', 'InvoicesController');
    Route::resource('invoice-items', 'InvoiceItemsController');
    Route::get('specific-client-invoices', 'InvoicesController@specificClientInvoices')->name('specific-client-invoices');
    Route::resource('payments', 'PaymentsController');
    Route::get('estimate-requests', 'EstimatesController@estimateRequests')->name('estimate-requests');
    Route::get('estimate-request-show/{id}', 'EstimatesController@estimateRequestShow')->name('estimate-request-show');
    Route::put('estimate-request-status-update', 'EstimatesController@estimateRequestStatusUpdate')->name('estimate-request-status-update');
    Route::resource('estimates', 'EstimatesController');
    Route::get('estimate-details/{id}', 'EstimatesController@estimateDetails')->name('estimate-details');
    Route::put('estimate-mark-as-project', 'EstimatesController@markAsProject')->name('estimate-mark-as-project');
    Route::put('update-estimate', 'EstimatesController@updateEstimate')->name('update-estimate');
    Route::resource('estimate-items', 'EstimatedItemsController');
    Route::get('estimate-discount', 'EstimatedItemsController@estimateDiscount')->name('estimate-discount');
    Route::put('estimate-discount/{id}', 'EstimatedItemsController@estimateDiscountUpdate');
    Route::get('esitmate-pdf-generate/{id}', 'EstimatedItemsController@estimatePdfGenerate')->name('esitmate-pdf-generate');

    Route::get('get-invoice-to-pay', 'InvoicesController@getInvoiceToPay')->name('get-invoice-to-pay');
    Route::prefix('settings')->group(function () {
        Route::get('other-setup', 'SettingsController@OtherSetup')->name('other-setup');
        Route::apiResources([
            'payment-methods' => 'PaymentMethodsController',
            'task-statuses'  => 'TaskStatusesController',
            'taxes'  => 'TaxesController',
        ]);
    });
});

Modules/Crm/Entities/Estimate.php
<?php

namespace Modules\Crm\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Modules\Crm\Entities\Client;
use Modules\Crm\Entities\ClientProject;
use Modules\Crm\Entities\EstimatedItem;
use Modules\Crm\Entities\Item;

class Estimate extends Model
{
	protected $connection = 'crm';
	protected $fillable = ['client_id', 'description', 'budget', 'example_link', 'status', 'discount', 'discount_type'];

	public function client()
	{
		return $this->belongsTo(Client::class, 'client_id', 'id');
	}

	public function estimateditems()
	{
		return $this->hasMany(EstimatedItem::class, 'estimate_id', 'id');
	}


	public function getRowTotalPercentage() {
	    return $this->estimateditems()->where('discount_type', 1)->sum(DB::raw('(quantity * rate) - ((rate * discount)/100)'));
	}

	public function getRowTotalFixedAmount() {
	    return $this->estimateditems()->where('discount_type', 2)->sum(DB::raw('(quantity * rate) - (quantity * discount)'));
	}

	public function project(){
		return $this->hasOne(ClientProject::class, 'estimate_id', 'id');
	}
}

Modules/Crm/Http/Controllers/EstimatesController.php
<?php

namespace Modules\Crm\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Modules\Crm\Entities\ClientProject;
use Modules\Crm\Entities\Estimate;
use Modules\Crm\Entities\EstimatedItem;
use Modules\Crm\Entities\Item;
use Yajra\DataTables\Facades\DataTables;

class EstimatesController extends Controller
{
    /*Note:: Status
    *1 for draft
    *2 for processing
    *3 for estimated
    *4 for invoiced
    *5 for cancel
    *6 for re-open
    */

    public function estimateRequests(Request $request)
    {
        if ($request->ajax()) {
            $estimates = Estimate::with('client')->whereIn('status', [1,2])->orderBy('updated_at', 'desc')->get();
            return Datatables::of($estimates)
                ->addIndexColumn()
                ->addColumn('estimateid', function ($estimate) {
                    $estimateId = '<a href="'.route('estimate-request-show',['id' => $estimate->id]).'" target="_blank" class="clickable">Request - '.$estimate->id.'</a>';
                    return $estimateId;
                })
                ->addColumn('created_at', function ($estimate) {
                    $createdAt = date('d M Y h:i a', strtotime($estimate->created_at));
                    return $createdAt;
                })
                ->addColumn('updated_at', function ($estimate) {
                    $updatedAt = date('d M Y h:i a', strtotime($estimate->updated_at));
                    return $updatedAt;
                })
                ->addColumn('status', function ($estimate) {
                    if ($estimate->status == 1) {
                        $status = '<span class="badge badge-pill badge-secondary mb-1">Draft</span>';
                    }elseif ($estimate->status == 2) {
                        $status = '<span class="badge badge-pill badge-primary mb-1">Processing</span>';
                    }
                    
                    return $status;
                })
                ->addColumn('action', function ($estimate) {
                    $btn = '<div class="table-actions">';
                    $btn .='<a class="edit-btn" type="button" data-toggle="modal" data-target="#estimateModal" data-whatever="1" data-id="'.$estimate->id.'"><i class="ik ik-edit-2"></i></a>';
                    $btn .='</div>';
                    return $btn;
                })
                ->rawColumns(['estimateid','created_at','updated_at', 'status','action'])
                ->make(true);
        }
        return view('crm::estimates.estimate-requests');
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */

    public function estimateRequestShow($id)
    {
        $estimateRequest = Estimate::with('client', 'estimateditems')->where('id', $id)->first();
        return view('crm::estimates.estimate-request-details', compact('estimateRequest'));
    }

    public function estimateRequestStatusUpdate(Request $request)
    {
        $id = $request->estimateid;
        $status = $request->status;
        $estimateRequest = Estimate::find($id);
        $estimateRequest->status = $status;
        $estimateRequest->save();
    }
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $estimates = Estimate::with('client')->whereNotIn('status', [1,2])->get();
            return Datatables::of($estimates)
                ->addIndexColumn()
                ->addColumn('estimateid', function ($estimate) {
                    $estimateId = '<a href="'.route('estimate-details',['id' => $estimate->id]).'" target="_blank" class="clickable">Estimate - '.$estimate->id.'</a>';
                    return $estimateId;
                })
                ->addColumn('created_at', function ($estimate) {
                    $createdAt = date('d M Y h:i a', strtotime($estimate->created_at));
                    return $createdAt;
                })
                ->addColumn('updated_at', function ($estimate) {
                    $updatedAt = date('d M Y h:i a', strtotime($estimate->updated_at));
                    return $updatedAt;
                })
                ->addColumn('status', function ($estimate) {
                    if ($estimate->status == 3) {
                        $status = '<span class="badge badge-pill badge-success mb-1">Estimated</span>';
                    }elseif ($estimate->status == 4) {
                        $status = '<span class="badge badge-pill badge-warning mb-1">Invoiced</span>';
                    }
                    
                    return $status;
                })
                ->addColumn('action', function ($estimate) {
                    $btn = '<div class="table-actions">';
                    $btn .='<a class="edit-btn" type="button" data-toggle="modal" data-target="#estimateModal" data-whatever="1" data-id="'.$estimate->id.'"><i class="ik ik-edit-2"></i></a>';
                    $btn .='</div>';
                    return $btn;
                })
                ->rawColumns(['estimateid','created_at','updated_at', 'status','action'])
                ->make(true);
        }
        return view('crm::estimates.list');
    }

    public function estimateDetails($id)
    {
        $estimate = Estimate::with('client')->find($id);

        // if ($estimate->discount_type == 1) {
        //     $estiamteTotal = $rowtotal =(($estItem->quantity * $estItem->item->rate) - (($estItem->item->discount * $estItem->item->rate)/100));
        // }

        return view('crm::estimates.estimate-details', compact('estimate'));
    }
    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('crm::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $rules = [
            'item' => 'required',
            'client' => 'required',

        ];
        $messages = [
            'item.required' => 'The item field is required.',
            'client.required' => 'The client field is required.',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();

        $item = Item::where('id', $request->item)->first();

        DB::beginTransaction();
        try {
            $estimate = new Estimate();
            $estimate->client_id   = $request->client;
            $estimate->description = $request->description;
            $estimate->budget      = $request->budget;
            $estimate->example_link = $request->examplelink;
            $estimate->status = 1;
            $estimate->save();

            $estimatedItem = new EstimatedItem();
            $estimatedItem->item_id = $item->id;
            $estimatedItem->rate = $item->rate;
            $estimatedItem->quantity = 1;
            $estimatedItem->discount = $item->discount;
            $estimatedItem->discount_type = $item->discount_type;
            $estimate->estimateditems()->save($estimatedItem);
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
        }
        
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {   
        return Estimate::with('estimateditems')->find($id);

        //return view('crm::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return Estimate::with('client')->find($id);
        //return view('crm::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'item' => 'required',
            'client' => 'required',

        ];
        $messages = [
            'item.required' => 'The item field is required.',
            'client.required' => 'The client field is required.',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();

        DB::beginTransaction();
        try {
            $estimate = Estimate::find($id);
            $estimate->client_id   = $request->client;
            $estimate->description = $request->description;
            $estimate->budget      = $request->budget;
            $estimate->example_link = $request->examplelink;
            $estimate->status = $request->status;
            $estimate->save();
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
        }
    }

    public function updateEstimate(Request $request)
    {
        $id = $request->esitmateid;
        $estimate = Estimate::find($id);
        if ($request->client) {
            $estimate->client_id = $request->client;
        }
        $estimate->description  = $request->description;
        $estimate->budget       = $request->budget;
        $estimate->example_link = $request->examplelink;
        $estimate->save();
    }
    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function markAsProject(Request $request)
    {
        $id = $request->estimateid;

        DB::beginTransaction();
        try {
            $estimate = Estimate::find($id);
            $estimate->status = 4;
            $estimate->save();

            $project = new ClientProject();
            $project->title = $request->title;
            $project->client_id = $estimate->client_id;
            $project->start_date = $request->startdate;
            $project->end_date = $request->enddate;
            $project->price = $request->price;

Modules/Crm/Resources/views/estimates/list.blade.php
@extends('crm::layouts.master')
@section('title')
{{__('Home')}}
@endsection
@section('content')
  
<div class="container-fluid">
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-file-text bg-blue"></i>
                    <div class="d-inline">
                        <h5>{{__('Estimates List')}}</h5>
                        <span>{{__('This is the list of the project estimate from client those are estimated or caceled.')}}</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{route('crm')}}"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="javascript:void(0)">{{__('Estimates')}}</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">{{__('List')}}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-block">
                    <h3 class="float-left"> {{__('Estimates List')}} </h3>
                </div>
                <div class="card-body">
                    <div class="dt-responsive">
                        <table id="estimateTable" class="table nowrap">
                            <thead>
                            <tr>
                                <th>{{__('#')}}</th>
                                <th>{{__('Estimate ID')}}</th>
                                <th>{{__('Client')}}</th>
                                <th>{{__('Budget')}}</th>
                                <th>{{__('Submitted At')}}</th>
                                <th>{{__('Updated At')}}</th>
                                <th>{{__('Status')}}</th>
                                <th class="text-center"><i class="ik ik-align-justify"></i></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Estimate Modal -->
<div class="modal animated zoomIn faster" id="estimateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">{{__('Edit Estimate')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="Form" action="javascript:void(0)">
                <div class="modal-body">
                    <div class="form-group row" id="client-box">
                        <label class="col-sm-4 col-lg-4 col-form-label">{{__('Client')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <select name="client" id="client" class="form-control select2" required>

                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-lg-4 col-form-label" for="exampleTextarea1">{{__('Description')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <textarea class="form-control" id="exampleTextarea1" rows="4" placeholder="{{__('Describe what you want done?')}}.." name="description"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-lg-4 col-form-label" for="budget">{{__('Budget')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <input type="text" class="form-control" placeholder="{{__('budget here')}}" name="budget" id="budget" value="0" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-lg-4 col-form-label" for="examplelink">{{__('Example Link')}}</label>
                        <div class="col-sm-8 col-lg-8">
                            <input type="text" class="form-control" placeholder="{{__('Work example link here')}}" name="examplelink" id="examplelink">
                        </div>
                    </div>
                    <input type="hidden" name="esitmateid" id="esitmateid">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('Close')}}</button>
                    <button type="submit" class="btn btn-primary update-btn">{{__('Update')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('extraJS')
<script>
    let eTable;
    $(document).ready(function () {
        eTable = $('#estimateTable').DataTable({
            processing: true,
            serverSide: true,
            orderable: false,
            ajax: "{{ route('estimates.index') }}",
            deferRender: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'estimateid', name: 'estimateid'},
                {data: 'client.name', name: 'client.name'},
                {data: 'budget', name: 'budget'},
                {data: 'created_at', name: 'created_at'},
                {data: 'updated_at', name: 'updated_at'},
                {data: 'status', name: 'status'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        /*--------------create form start---------*/
        $('.modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var modal = $(this);
            var id = button.data('id');

            $.ajax({
                url: '{{route('estimates.index')}}/' + id + '/edit',
                type: 'GET',
                data: {id},
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    if (response.status != 4) {
                        modal.find('#client').val(response.client_id).trigger('change');
                    }else{
                        document.getElementById("client").disabled = true;
                    }

                    modal.find('textarea[name=description]').val(response.description);
                    modal.find('input[name=budget]').val(response.budget);
                    modal.find('input[name=examplelink]').val(response.example_link);
                    modal.find('input[name=esitmateid]').val(response.id);

                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                    console.log(data);
                }
            });
            
        });
        /*--------------create form end----------*/

        loadClient();


        /*--------------updating estimate start--------------*/
        $(document).on('click', '.update-btn', function () {
            let data = $('#Form').serialize();
            $.ajax({
                url: "{{ route('update-estimate')}}/",
                type: 'PUT',
                data: data,
                beforeSend: function (request) {
                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                },
                success: function (response) {
                    $('#estimateModal').modal('toggle');
                    $('#Form').trigger("reset");
                    showSuccessToast('{{__("Updated Successfully")}}');
                    eTable.draw(false);
                    console.log(response);
                },
                error: function (data) {
                    let msg = '';
                    if (data.responseJSON.errors) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            msg += '<p">' + error[0] + '</p>';
                        });
                    } else {
                        msg = data.responseJSON.message;
                    }
                    showDangerToast(msg);
                }
            });
            
        });
        /*--------------updating estimate end---------------*/
    });
    function loadClient(){
        $.ajax({
            url: '{{route('client-name-id')}}',
            type: 'GET',
            beforeSend: function (request) {
                return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
            },
            success: function (response) {
               $('#client').empty();
               $.each(response, function (i, client) {
                   $('#client').append($('<option>', {
                       value: client.id,
                       text: client.name
                   }));
               });
            },
            error: function (data) {
                let msg = '';
                if (data.responseJSON.errors) {
                    $.each(data.responseJSON.errors, function (i, error) {
                        msg += '<p">' + error[0] + '</p>';
                    });
                } else {
                    msg = data.responseJSON.message;
                }
                showDangerToast(msg);
                console.log(data);
            }
        });
    }
</script>
@endsection