Modules/Hrm/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('hrm')->group(function () {
    Route::get('/', 'HrmController@index')->name('hrm');
    Route::prefix('employee')->group(function () {
        Route::get('/departments/all', 'DepartmentController@all')->name('department.all');
        Route::get('/positions/all', 'PositionController@all')->name('position.all');
        Route::get('/divisions/all', 'DivisionController@all')->name('division.all');
        Route::get('/employees/all', 'EmployeeController@all')->name('employee.all');
        Route::apiResources([
            'departments' => 'DepartmentController',
            'positions' => 'PositionController',
            'divisions' => 'DivisionController',
            'employees' => 'EmployeeController',
            'reschedules' => 'RescheduleController',
        ]);
        Route::name('employees.')->group(function () {
            Route::apiResource('documents', 'EmployeeDocController');
        });
    });
    Route::get('/job-type/all', 'JobTypeController@all')->name('job_type.all');
    Route::get('/shift-schedules/all', 'ShiftScheduleController@all')->name('shift_schedule.all');
    Route::apiResources([
        'allowances' => 'AllowanceController',
        'shift-schedules' => 'ShiftScheduleController',
        'attendances' => 'AttendanceController',
        'loans' => 'LoanController',
    ]);
    Route::prefix('loan')->group(function () {
        Route::get('employees/{employee}/installments/{date?}', 'LoanInstallmentController@installment')->name('loans.employee.installment');
        Route::apiResources([
            'installments' => 'LoanInstallmentController',
        ]);
    });
    Route::prefix('salaries')->name('salaries.')->group(function () {
        Route::apiResource('/generate', 'SalaryGenerationController')->only(['index', 'store']);
        Route::get('/salary/{salary}/change-status', 'SalaryController@changeStatus')->name('salary.change-status');
        Route::apiResource('/salary', 'SalaryController');
    });

    Route::prefix('leave')->name('leave.')->group(function () {
        Route::get('/types/all', 'LeaveTypeController@all')->name('types.all');
        Route::apiResources([
            'holidays' => 'HolidayController',
            'types' => 'LeaveTypeController',
            'applications' => 'LeaveApplicationController',
        ]);
    });
    Route::get('/grade/all', 'GradeController@all')->name('grade.all');
    Route::apiResource('grades', 'GradeController');

    Route::prefix('trainings')->name('trainings.')->group(function () {
        Route::get('/types/all', 'TrainingTypeController@all')->name('types.all');
        Route::get('/trainers/all', 'TrainerController@all')->name('trainers.all');
        Route::apiResources([
            'types' => 'TrainingTypeController',
            'trainers' => 'TrainerController',
            'workshops' => 'WorkshopController',
        ]);
    });
    Route::prefix('report')->name('report.')->group(function () {
        Route::get('loan', 'ReportController@loan')->name('loan');
    });
    Route::name('hrm.')->group(function () {
        Route::apiResources([
            'settings' => 'SettingsController',
        ]);
    });

//    Common Menu items
    Route::get('/notices', 'Common\NoticeController@index')->name('hrm.notices.index');
    Route::get('/messenger', 'Common\MessengerController@index')->name('hrm.messenger.index');
    Route::get('/calender', 'Common\CalenderController@index')->name('hrm.calender.index');
    Route::get('/activities', 'Common\ActivityController@index')->name('hrm.activities.index');
    Route::get('/users', 'Common\UserController@index')->name('hrm.users.index');
    Route::get('/roles', 'Common\RoleController@index')->name('hrm.roles.index');
    Route::get('/user-role', 'Common\UserRoleController@index')->name('hrm.user-role.index');
    Route::get('/role-permission', 'Common\RolePermissionController@index')->name('hrm.role-permission.index');
    Route::get('/user-permission', 'Common\UserPermissionController@index')->name('hrm.user-permission.index');
    Route::get('/languages', 'Common\LanguageController@index')->name('hrm.languages.index');
    Route::get('/languages/{language}/phrases', 'Common\LanguagePhraseController@index')->name('hrm.languages.phrases.index');
    Route::get('/phrases', 'Common\PhraseController@index')->name('hrm.phrases.index');
    Route::get('/currencies', 'Common\CurrencyController@index')->name('hrm.currencies.index');
    Route::get('/profile', 'Common\ProfileController@index')->name('hrm.profile.index');
});

Modules/Hrm/Http/Controllers/ReportController.php
<?php

namespace Modules\Hrm\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Modules\Hrm\Entities\Allowance;
use Modules\Hrm\Entities\Employee;
use Yajra\DataTables\Facades\DataTables;

class ReportController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function loan(Request $request)
    {
        if ($request->ajax()) {
            $employees = Employee::with('official.division', 'loan', 'installment')->get();
            return Datatables::of($employees)
                ->addIndexColumn()
                ->addColumn('division', function ($employee) {
                    if ($employee->official->division) {
                        return $employee->official->division()->first()->name;
                    }
                })
                ->addColumn('department', function ($employee) {
                    if ($employee->official->division) {
                        return $employee->official->division()->first()->department->name;
                    }
                })
                ->addColumn('loan', function ($employee) {
                    return $employee->loan->sum('amount');
                })
                ->addColumn('installment', function ($employee) {
                    return $employee->installment->sum('paid');
                })
                ->make(true);
        }
        return view('hrm::reports.loan');
    }

}

Modules/Hrm/Resources/views/reports/loan.blade.php
@extends('hrm::master')
@section('title')
    {{__('Report')}}
@endsection
@section('content')
    <div class="container-fluid">
        <div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-inbox bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{__('Loan')}}</h5>
                            <span>{{__('Loan status of Employees')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('hrm')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0)">{{__('Report')}}</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{__('Loan')}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-block">
                        <h3 class="float-left"> {{__('Loans')}} </h3>
                    </div>
                    <div class="card-body">
                        <div class="dt-responsive">
                            <table id="#" class="table nowrap">
                                <thead>
                                <tr>
                                    <th>{{__('ID')}}</th>
                                    <th>{{__('Employee')}}</th>
                                    <th>{{__('Division')}}</th>
                                    <th>{{__('Department')}}</th>
                                    <th>{{__('Loan')}}</th>
                                    <th>{{__('Paid')}}</th>
                                    <th>{{__('Due')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('extraJS')
    <script>
        $(document).ready(function () {
            var oTable = $('.table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('report.loan') }}",
                deferRender: true,
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'division', name: 'division'},
                    {data: 'department', name: 'department'},
                    {data: 'loan', name: 'loan'},
                    {data: 'installment', name: 'installment'},
                    {
                        data: null, name: 'due', render: function (data, type, row) {
                            let due = Math.round(data.loan - data.installment);
                            if(due>0){
                                return "<span class='text-warning'>"+due+"</span>";
                            }
                            return due;
                        }
                    },
                ]
            });
        });
    </script>
@endsection